export {LoginPage} from "./auth/Login";
export {WelcomePage} from "./auth/Welcome";
export {HomePage} from "./Home";
export {ErrorPage} from "./Error";
export {Meet} from "./rdv/Meet";
export {RDVMeet} from "./rdv/Apercu";
export {RDVList} from "./rdv/List";
export {Account} from "./Account";
export {RDVAgenda} from "./rdv/Agenda";